/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = AdminDashboard.SwaggerClientHelpers.SwaggerDateConverter;

namespace AdminDashboard.Models.SwaggerModels
{
    /// <summary>
    /// Defines DenominationClassType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum DenominationClassType
    {
        /// <summary>
        /// Enum BTech for value: BTech
        /// </summary>
        [EnumMember(Value = "BTech")]
        BTech = 1,
        /// <summary>
        /// Enum Cancel for value: Cancel
        /// </summary>
        [EnumMember(Value = "Cancel")]
        Cancel = 2,
        /// <summary>
        /// Enum CashIn for value: CashIn
        /// </summary>
        [EnumMember(Value = "CashIn")]
        CashIn = 3,
        /// <summary>
        /// Enum CashU for value: CashU
        /// </summary>
        [EnumMember(Value = "CashU")]
        CashU = 4,
        /// <summary>
        /// Enum CashUTopUp for value: CashUTopUp
        /// </summary>
        [EnumMember(Value = "CashUTopUp")]
        CashUTopUp = 5,
        /// <summary>
        /// Enum Donation for value: Donation
        /// </summary>
        [EnumMember(Value = "Donation")]
        Donation = 6,
        /// <summary>
        /// Enum EducationService for value: EducationService
        /// </summary>
        [EnumMember(Value = "EducationService")]
        EducationService = 7,
        /// <summary>
        /// Enum ElectricityBill for value: ElectricityBill
        /// </summary>
        [EnumMember(Value = "ElectricityBill")]
        ElectricityBill = 8,
        /// <summary>
        /// Enum ElectricityCard for value: ElectricityCard
        /// </summary>
        [EnumMember(Value = "ElectricityCard")]
        ElectricityCard = 9,
        /// <summary>
        /// Enum Etisalat for value: Etisalat
        /// </summary>
        [EnumMember(Value = "Etisalat")]
        Etisalat = 10,
        /// <summary>
        /// Enum Itunes for value: Itunes
        /// </summary>
        [EnumMember(Value = "Itunes")]
        Itunes = 11,
        /// <summary>
        /// Enum OneCard for value: OneCard
        /// </summary>
        [EnumMember(Value = "OneCard")]
        OneCard = 12,
        /// <summary>
        /// Enum OrangeInternet for value: OrangeInternet
        /// </summary>
        [EnumMember(Value = "OrangeInternet")]
        OrangeInternet = 13,
        /// <summary>
        /// Enum OrangeMobile for value: OrangeMobile
        /// </summary>
        [EnumMember(Value = "OrangeMobile")]
        OrangeMobile = 14,
        /// <summary>
        /// Enum Petrotrade for value: Petrotrade
        /// </summary>
        [EnumMember(Value = "Petrotrade")]
        Petrotrade = 15,
        /// <summary>
        /// Enum TelecomeEgypt for value: TelecomeEgypt
        /// </summary>
        [EnumMember(Value = "TelecomeEgypt")]
        TelecomeEgypt = 16,
        /// <summary>
        /// Enum Topup for value: Topup
        /// </summary>
        [EnumMember(Value = "Topup")]
        Topup = 17,
        /// <summary>
        /// Enum University for value: University
        /// </summary>
        [EnumMember(Value = "University")]
        University = 18,
        /// <summary>
        /// Enum ValU for value: ValU
        /// </summary>
        [EnumMember(Value = "ValU")]
        ValU = 19,
        /// <summary>
        /// Enum VodafoneInternet for value: VodafoneInternet
        /// </summary>
        [EnumMember(Value = "VodafoneInternet")]
        VodafoneInternet = 20,
        /// <summary>
        /// Enum VodafoneMobile for value: VodafoneMobile
        /// </summary>
        [EnumMember(Value = "VodafoneMobile")]
        VodafoneMobile = 21,
        /// <summary>
        /// Enum Voucher for value: Voucher
        /// </summary>
        [EnumMember(Value = "Voucher")]
        Voucher = 22,
        /// <summary>
        /// Enum WaterBill for value: WaterBill
        /// </summary>
        [EnumMember(Value = "WaterBill")]
        WaterBill = 23,
        /// <summary>
        /// Enum WEInternet for value: WEInternet
        /// </summary>
        [EnumMember(Value = "WEInternet")]
        WEInternet = 24,
        /// <summary>
        /// Enum WEInternetExtra for value: WEInternetExtra
        /// </summary>
        [EnumMember(Value = "WEInternetExtra")]
        WEInternetExtra = 25    }
}
