/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = AdminDashboard.SwaggerClientHelpers.SwaggerDateConverter;

namespace AdminDashboard.Models.SwaggerModels
{
    /// <summary>
    /// EditDenominationModel
    /// </summary>
    [DataContract]
        public partial class EditDenominationModel :  IEquatable<EditDenominationModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EditDenominationModel" /> class.
        /// </summary>
        /// <param name="denomination">denomination.</param>
        /// <param name="denominationServiceProviders">denominationServiceProviders.</param>
        /// <param name="denominationParameters">denominationParameters.</param>
        /// <param name="denominationReceipt">denominationReceipt.</param>
        public EditDenominationModel(DenominationModel denomination = default(DenominationModel), List<DenominationServiceProvidersModel> denominationServiceProviders = default(List<DenominationServiceProvidersModel>), List<DenominationParameterModel> denominationParameters = default(List<DenominationParameterModel>), DenominationReceiptModel denominationReceipt = default(DenominationReceiptModel))
        {
            this.Denomination = denomination;
            this.DenominationServiceProviders = denominationServiceProviders;
            this.DenominationParameters = denominationParameters;
            this.DenominationReceipt = denominationReceipt;
        }
        
        /// <summary>
        /// Gets or Sets Denomination
        /// </summary>
        [DataMember(Name="denomination", EmitDefaultValue=false)]
        public DenominationModel Denomination { get; set; }

        /// <summary>
        /// Gets or Sets DenominationServiceProviders
        /// </summary>
        [DataMember(Name="denominationServiceProviders", EmitDefaultValue=false)]
        public List<DenominationServiceProvidersModel> DenominationServiceProviders { get; set; }

        /// <summary>
        /// Gets or Sets DenominationParameters
        /// </summary>
        [DataMember(Name="denominationParameters", EmitDefaultValue=false)]
        public List<DenominationParameterModel> DenominationParameters { get; set; }

        /// <summary>
        /// Gets or Sets DenominationReceipt
        /// </summary>
        [DataMember(Name="denominationReceipt", EmitDefaultValue=false)]
        public DenominationReceiptModel DenominationReceipt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EditDenominationModel {\n");
            sb.Append("  Denomination: ").Append(Denomination).Append("\n");
            sb.Append("  DenominationServiceProviders: ").Append(DenominationServiceProviders).Append("\n");
            sb.Append("  DenominationParameters: ").Append(DenominationParameters).Append("\n");
            sb.Append("  DenominationReceipt: ").Append(DenominationReceipt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EditDenominationModel);
        }

        /// <summary>
        /// Returns true if EditDenominationModel instances are equal
        /// </summary>
        /// <param name="input">Instance of EditDenominationModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EditDenominationModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Denomination == input.Denomination ||
                    (this.Denomination != null &&
                    this.Denomination.Equals(input.Denomination))
                ) && 
                (
                    this.DenominationServiceProviders == input.DenominationServiceProviders ||
                    this.DenominationServiceProviders != null &&
                    input.DenominationServiceProviders != null &&
                    this.DenominationServiceProviders.SequenceEqual(input.DenominationServiceProviders)
                ) && 
                (
                    this.DenominationParameters == input.DenominationParameters ||
                    this.DenominationParameters != null &&
                    input.DenominationParameters != null &&
                    this.DenominationParameters.SequenceEqual(input.DenominationParameters)
                ) && 
                (
                    this.DenominationReceipt == input.DenominationReceipt ||
                    (this.DenominationReceipt != null &&
                    this.DenominationReceipt.Equals(input.DenominationReceipt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Denomination != null)
                    hashCode = hashCode * 59 + this.Denomination.GetHashCode();
                if (this.DenominationServiceProviders != null)
                    hashCode = hashCode * 59 + this.DenominationServiceProviders.GetHashCode();
                if (this.DenominationParameters != null)
                    hashCode = hashCode * 59 + this.DenominationParameters.GetHashCode();
                if (this.DenominationReceipt != null)
                    hashCode = hashCode * 59 + this.DenominationReceipt.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
